[tool.poetry]
name = "gitops"
version = "0.10.4"
description = "Manage multiple apps across one or more k8s clusters."
authors = ["Jarek GÅ‚owacki <jarekwg@gmail.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.11"
# CLI requirements
invoke = "*"
pyyaml = ">=6.0.1"
dsnparse = "*"
colorama = "^0.4.4"
boto3 = "*"
humanize = "^3.5.0"
tabulate = "^0.8.9"
# Server requirements
fastapi = { version = "*", optional = true }
httpx = { version = ">=0.18.1,<0.24.0", optional = true }
uvicorn = { version = "^0.17.0", optional = true }
sentry-sdk = { version = "^1.3.0", optional = true }
kubernetes_asyncio = { version = "^25.1.2", optional = true }

[tool.poetry.extras]
server = [
    "fastapi",
    "uvicorn",
    "httpx",
    "uvicorn",
    "sentry-sdk",
    "kubernetes_asyncio",
]

[tool.poetry.dev-dependencies]
ruff = "^0.2.0"
isort = "*"
ipdb = "*"
python-dotenv = "*"
pytest = "*"
requests = "^2.25.1"
pre-commit = "^2.13.0"
mypy = "^1.8.0"
black = "*"
pytest-asyncio = "^0.20.3"

[tool.poetry.scripts]
gitops = 'gitops.main:program.run'

# Use this to seperate our CLI and Server requirements. poetry install -E server
#[tool.poetry.extras]
#server = ["fastapi", "uvicorn", "httpx"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
# Generated by the 'nitpick init' command
# More info at https://nitpick.rtfd.io/en/latest/configuration.html
style = [
    'https://raw.githubusercontent.com/uptick/.github/main/nitpick/python.toml',
    'py://nitpick/resources/any/commitizen',
]
cache = "never"