
[project]
name = "gitops"
version = "0.11.4"
description = "Manage multiple apps across one or more k8s clusters."
requires-python = ">=3.12"
readme = "README.md"
authors = [{name = "Jarek GÅ‚owacki",email = "jarekwg@gmail.com"}]
dependencies = [
    "invoke>=2.2.0",
    "pyyaml>=6.0.2",
    "dsnparse==0.2.1",
    "colorama>=0.4.4",
    "boto3==1.35.4",
    "humanize>=3.5.0",
    "tabulate>=0.8.9",
    "packaging>=24.1",
]

[project.scripts]
gitops = "gitops.main:program.run"


[project.optional-dependencies]
server = [
    "httpx>=0.23.0,<0.24.0",
    "uvicorn>=0.17.6",
    "fastapi==0.109.2",
    "kubernetes_asyncio>=25.1.2",
    "sentry-sdk>=1.3.0",
    "uptick-observability[fastapi]>=0.2.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
    "ruff>=0.6.3",
    "types-colorama>=0.4.15.20240311",
    "mypy>=1.11.2",
    "types-pyyaml>=6.0.12.20240808",
    "types-tabulate>=0.9.0.20240106",
    "boto3-stubs>=1.35.11",
    "pytest-asyncio>=0.24.0",
]


[tool.uv.sources]

[tool.nitpick]
# Generated by the 'nitpick init' command
# More info at https://nitpick.rtfd.io/en/latest/configuration.html
style = [
    'https://raw.githubusercontent.com/uptick/.github/main/nitpick/python.toml',
    'py://nitpick/resources/any/commitizen',
]
cache = "never"

[tool.mypy]
exclude = ["tests"]
